[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
fs_permissions = [{ access = "read-write", path = "./data" }]

[dependencies]
flare-periphery = "0.1.37"
"@openzeppelin-contracts" = "5.2.0-rc.1"
surl = { version = "0.0.0", git = "https://github.com/memester-xyz/surl.git", rev = "5f92a5260c8e0198ca3ee6a16255d6cda4e0887a" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
